### ISSUE TITLE
Can not add a two sensor package via QR code

### ISSUE THREAD

**Issue by groissi** [VincentMasselis/TPMS-advanced#14]
Due to the fact that a motorbike or a single axle trailer only has two wheels, I've ordered a package with two sensors for my motorbike. There was a one-click-binding QR code shipped with it, that only contains the address of two sensors instead of four.

Your QR code scanner logic only accepts a four code QR code text like '11AD8B&21563D&31A4F0&41A552' from your QR code sample. As mentioned my delivered code contains only two sensor addressed and looks like '1244BD&22191C'. I also attach the picture of the QR code card delivered at the bottom.

Could you please enhance the QR code scanner to also accept only two sensors, especially for the vehicle types 'motorbike' and 'single axle trailer'? Would be much appreciated.

![qr_code_motorbike-tinified](https://github.com/VincentMasselis/TPMS-advanced/assets/5651429/4d9f5769-e06c-434e-a4e1-570cb5f5d29d)

**Comment by VincentMasselis** [comment]
Hello @groissi, thanks for submitting an issue and contributing for the app !

Until now, I've never seen a 2 wheel only packaging and the associated QR-code, thanks to the photo you filled, I can update the business logic which parse it.

An associated pull request will be opened soon to handle this. :)
