### ISSUE TITLE
Motorcycle sketch picture proposal

### ISSUE THREAD

**Issue by groissi** [VincentMasselis/TPMS-advanced#16]
Hej @VincentMasselis,
I know it's definitely not a very good one, but it could be a start ☺️ What do you think?!
Sorry, I have to paste a Link ([schema_motorcycle_top_view.webp](https://mega.nz/file/6woyCJjb#Z5W9SPlgj-iUojbrSdBSFNVTNy8xuiWcagvenkqAepg)), because I couldn't upload a webp File.

**Comment by VincentMasselis** [comment]
Hello @groissi and thanks for you suggestion !

I think the motorcycle image you suggested is too far from the look and feel of the current car picture but I you have time (and photoshop skills 😅) you can try to create a new one which is closer to what the app needs :)

**Comment by zenyagami** [comment]
hello @VincentMasselis  I paid for a gig in fiverr so this should be copyright free and you can use it , 
![Bike illustration2-01](https://github.com/VincentMasselis/TPMS-advanced/assets/1240069/623397ee-d069-4f18-86b9-e32116e018fc)
I also have the source file .ai extension, but if you need it let me know!
so it would be free to use in the app

**Comment by VincentMasselis** [comment]
Hello @zenyagami and thanks for you contribution !
I definitively love it, I'll add your picture proposal to the motorcycle layout

**Comment by VincentMasselis** [comment]
There it is:
![4](https://github.com/VincentMasselis/TPMS-advanced/assets/6769250/2758d0ba-9c12-4b26-9639-c0a3b1369f8f)

What do you think about ?

**Comment by zenyagami** [comment]
Looks good

**Comment by VincentMasselis** [comment]
A beta with includes this sketch was published this week:
https://play.google.com/store/apps/details?id=com.masselis.tpmsadvanced

**Comment by VincentMasselis** [comment]
Released in production this afternoon
