### ISSUE TITLE
Support for Bluetooth low energy TPMS

### ISSUE THREAD

**Issue by psoukal-nonms** [VincentMasselis/TPMS-advanced#21]
Could you kindly look to support BLE (Bluetooth 5 low energy) tyre pressure devices. They use 8 digit hexadecimal identifiers and are normally paired over Bluetooth rather than by scanning a QR code and are paired one by one.

Here are 2 sample IDs, note they aren’t ordered 1,2,3,4 like those already supported.

FD2F46B2
95365F44

Thanks!

**Comment by VincentMasselis** [comment]
Hello and thanks for submitting and issue !

Could you provide me a link where I can show which kind of sensor you're talking about ? I've 2 packs a sensors which uses BLE 5 and both of them are working correctly with TPMS Advanced.

**Comment by psoukal-nonms** [comment]
Bluetooth 5.0 2/3/4 TPMS Sensors Motorcycle Car Tire Pressure Monitoring
System 0-100PSI Tyre https://a.aliexpress.com/_mLq6ziA


Regards,
Peter

**Comment by psoukal-nonms** [comment]
Here’s the data you requested. I think these are from two of my TPMS.

Let me know what you find.



Regards,
Peter

**Comment by VincentMasselis** [comment]
Unfortunately I can't see any data in your response. Could you consider using the github website directly instead of using mails please ?

**Comment by psoukal-nonms** [comment]
Here's the data froimages, apologies they didn't come through to you.

DC:A5:73:92:8D:DB NOT BONDED CONNECT 7-106 dBm # 2005 ms Device type:
UNKNOWN Advertising type: Legacy Flags: GeneralDiscoverable,
BrEdrNotSupported Complete list of 16-bit Service UUIDs: OxFEED Service
Data: UUID: OxFEED *Data: Ox0200E14CEA12AE41634C*

DC:A5:73:92:8D:DB NOT BONDED CONNECT 7-106 dBm # 2005 ms Device type:
UNKNOWN Advertising type: Legacy Flags: GeneralDiscoverable,
BrEdrNotSupported Complete list of 16-bit Service UUIDs: OxFEED Service
Data: UUID: OxFEED *Data: Ox0200E14CEA12AE41634C*


Regards,
Peter

**Comment by VincentMasselis** [comment]
Theses data are unusual, TPMS Advanced used to parse a bloc of 15 bytes while your sample is 10 bytes only. On the "official" app SYTPMS, which data do you have ? Does temperature, pressure and battery are displayed ? 

Since the byte array length's is different and the service uuids uses a different key, I think your sensor works with a new format (or an old format) that I've nerver seen.

**Comment by psoukal-nonms** [comment]
This is an example of the data I see in the app:

2.6Bar 15.0°C 2.9V


Regards,
Peter

**Comment by aetha** [comment]
I'm having the same issue with mine, these ones: https://www.aliexpress.com/item/1005005286360131.html 

They work in SYTPMS, (but not TPMSII)
![Screenshot_20231004-142829.jpg](https://github.com/VincentMasselis/TPMS-advanced/assets/3007450/b5759337-20f4-46a6-adc7-14c14918e074)

nRF Connect gave me this info 
![Screenshot_20231004-142918.jpg](https://github.com/VincentMasselis/TPMS-advanced/assets/3007450/292eb812-31e1-4809-a7c9-a3e850f97768)

Copied raw data for each:
```
0x0303A5270308425208FF801E1301BE9720
0x0303A5270308425208FF201C1101992FEB
```

**Comment by VincentMasselis** [comment]
Hello @aetha and thanks for you contribution !

Fortunately I bought one of theses sensors 1 month ago (those with a sticker containing 2 hexa chars on the top and the location on the bottom). I'm still reverse engineering them in order to understand which kind of data is sent through theses sensor.
The compatibility with theses sensors is my next feature :)

**Comment by VincentMasselis** [comment]
Good news, I'm working to manage the sensors both of you are currently using. Theses sensors manufacturer by Pecham are not working like Sysgration does, tyre location is not returned but the sensor itself, it's up to the user to tell where the sensor is located. This said, I'm currently working an a new screen to pair the Pecham sensor is a easy and natural way.

I've a quick question for you @aetha and @psoukal-nonms, to make my sensors visible when attached to a pressured way **AND** the wheel must be spinning, do your sensors are only visible in this conditions like me ? How did you pair yours when using the """official""" app ?

**Comment by psoukal-nonms** [comment]
That’s good news. When do you expect the app to be in the play store?

The sytmps app has you pair an individual sensor at a time.

By screwing in the sensor into a tyre stem it allows it to be pair. If it’s
already on the tyre I unscrew and rescrew it so it becomes pressurised. The
wheel does not need to be spinning to pair.

Does this make sense?

Regards,
Peter

**Comment by aetha** [comment]
My experience has been the same as @psoukal-nonms, unscrewing & then re-tightening them to cause a pressure fluctuation, forces them to wake up. No need to move the wheels to pair.

**Comment by VincentMasselis** [comment]
Thanks both of you, I'm working on an user experience which match this technical behavior in order to make it as best as possible.

**Comment by VincentMasselis** [comment]
Hey !
I just pushed a release which include a support for the Pecham sensors into the beta channel of the Play Store. If you want to try this new version, follow [this link](https://play.google.com/apps/testing/com.masselis.tpmsadvanced) to become a beta tester.
