### ISSUE TITLE
15 Psi offset

### ISSUE THREAD

**Issue by 2solt** [VincentMasselis/TPMS-advanced#28]
**Describe the bug**
For me there is a 15Psi (atmoshperic) differnce compare to the SYTPMS app. (pecham sensor)
Currenly showing:
TPMS-Advanced: Front: 47 psi Rear 51 psi 
SYTPMS: Front: 32.2 Psi Rear: 36.3 Psi 

**Expected behavior**
Not shure wich one show the correct value when the tyres are inflated, I have not verified it with another device.

**Comment by VincentMasselis** [comment]
Hello @2solt and thank you for contributing for the app !
I'll check on my side which values are correct between TPMS-Advanced and the original Pecham app, I will try with my inflator which display the current pressure ;)

**Comment by 2solt** [comment]
Thanks for creating it, I just veirfied on the petrol station looks like TPMS-Advanced is off by 15 Psi
Here is my raw data: 0x0303A5270308425208FF80201401D48344 
(wich is 32.Psi, 18.0°C, 3.2V in SYTPMS and 47Psi on TPMS-Advanced the temperature is the same 18.0°C)

**Comment by zenyagami** [comment]
I tried the fix in the pr but interesting enough I have different data, I'll attach the result hex, but I'm the app shows 3.0bar and in the app (using the psi branch) it displays 0.6 bar 🙉
I'm not sure if the bye 3-4 should be used only from here,
https://github.com/andi38/TPMS
I'll do more test later. Thanks a lot for the effort

**Comment by 2solt** [comment]
Works for me 
![atpms](https://github.com/VincentMasselis/TPMS-advanced/assets/10811994/b1538cc4-f3a6-470e-b9bb-9a467e02136d)

**Comment by VincentMasselis** [comment]
@2solt Great and thanks to trying it !

I also have to try on my side, if OK, I'll create a release, probably the next month

**Comment by VincentMasselis** [comment]
A beta with includes this sketch was published this week:
https://play.google.com/store/apps/details?id=com.masselis.tpmsadvanced
